function out = dgsoln(x,A,i,nodes,nt,dx,ecent)
    out   =     A(1,i,nt)*lag((2.0/dx)*(x-ecent(i)),0,5,nodes) + ...
                A(2,i,nt)*lag((2.0/dx)*(x-ecent(i)),1,5,nodes) + ...
                A(3,i,nt)*lag((2.0/dx)*(x-ecent(i)),2,5,nodes) + ...
                A(4,i,nt)*lag((2.0/dx)*(x-ecent(i)),3,5,nodes) + ...
                A(5,i,nt)*lag((2.0/dx)*(x-ecent(i)),4,5,nodes) + ...
                A(6,i,nt)*lag((2.0/dx)*(x-ecent(i)),5,5,nodes);
end